image: docker:stable

services:
  - docker:dind
  
variables:
  DOCKER_DRIVER: overlay2
  DEBIAN_FRONTEND: noninteractive
  
before_script:
  - docker login -u "$ALIYUN_REGISTRY_LOGIN" -p "$ALIYUN_REGISTRY_PASSWD" $ALIYUN_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  except:
    - master
  tags:
    - docker-build
